[package]
name = "aurora_services"
version = "0.1.0"
edition = "2024"
description = "Aurora OS platform services (settings, notifications, device info)"
authors = ["Maksim Leiman <maximleyman@yandex.ru>"]
license = "Apache 2.0"
keywords = ["aurora-os", "sailfish-os"]
readme = "README.md"
repository = "https://github.com/auroraos-rs/aurora_services"
exclude = ["/.cargo"]

[dependencies]
dbus = "0.9"
notify-rust = { version = "4", default-features = false, features = ["d"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0"
